<?php

namespace MetCardBundle\Repository;

/**
 * DiagnosisRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DiagnosisRepository extends \Doctrine\ORM\EntityRepository
{
}
