<?php

namespace MetCardBundle\Repository;

/**
 * ExaminationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ExaminationRepository extends \Doctrine\ORM\EntityRepository
{
}
