<?php

namespace MetCardBundle\Repository;

/**
 * ProceedingsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProceedingsRepository extends \Doctrine\ORM\EntityRepository
{
}
