<?php

namespace MetCardBundle\Repository;

/**
 * RescueTeamRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RescueTeamRepository extends \Doctrine\ORM\EntityRepository
{
}
